version: "3.8"
services:
  web-server:
    build:
      context: ./src
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - /src/node_modules
    networks:
      - web-server-network
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
    networks:
      - web-server-network

networks:
  web-server-network:
    driver: bridge